version: "3"
services:
  squid-proxy:
    build: "."
    environment:
      - CN=proxy.mountaineersupport.local
      - O=proxy
      - OU=proxy
      - C=US
    ports:
      - "3128:3128"
      - "4128:4128"
    volumes:
      - ./log:/var/log/
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./cache:/var/cache
      - ./cert:/etc/squid-cert
    restart: always